# Generated by Django 5.2.17 on 2026-08-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("character", models.CharField(max_length=120)),
                ("series", models.CharField(max_length=120)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Ex. 'Chapitre 24', 'Épisode 5, saison 1'.",
                        max_length=120,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("determination", "Détermination"),
                            ("loss", "Perte"),
                            ("friendship", "Amitié"),
                            ("ambition", "Ambition"),
                            ("wisdom", "Sagesse"),
                            ("defiance", "Défi"),
                            ("freedom", "Liberté"),
                            ("fear", "Peur"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["series", "character"],
            },
        ),
    ]
