# Generated by Django 5.2.17 on 2026-08-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="fr_origin",
            field=models.CharField(
                blank=True,
                choices=[
                    ("community", "Traduction communautaire"),
                    ("assisted", "Traduction assistée (non vérifiée)"),
                ],
                help_text="Provenance de text_fr — laissé vide si aucune traduction n'existe.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="text_fr",
            field=models.TextField(
                blank=True,
                help_text="Traduction française. Voir fr_origin pour sa provenance/fiabilité.",
            ),
        ),
    ]
